name: Full Stack Deployment

on:
  workflow_dispatch:

jobs:
  backend:
    name: Deploy Backend
    uses: ./.github/workflows/backend-deploy.yml

  frontend:
    name: Deploy Frontend
    uses: ./.github/workflows/frontend-deploy.yml
